name: khata_pro
description: Mummy Ka Khata PRO BLACK 2026
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.3
  path_provider: ^2.1.5
  fl_chart: ^0.71.0
  share_plus: ^11.0.0
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
